language: cpp

sudo: false

compiler:
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then wget http://asset.rubini.us/prebuilt/llvm-3.6-x86_64-pc-linux-gnu-gcc-4.7.tar.bz2; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then mkdir -p vendor/llvm; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then tar -C vendor/llvm -xjf llvm-3.6-x86_64-pc-linux-gnu-gcc-4.7.tar.bz2; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then export LLVM_CONFIG=`pwd`/vendor/llvm/Release+Asserts/bin/llvm-config; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm && brew link --force llvm; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then export LLVM_CONFIG=/usr/local/opt/llvm/bin/llvm-config; fi
  - $LLVM_CONFIG --version
  - rvm use $RVM --install --binary --fuzzy
  - gem update --system
  - gem --version

before_script:
  - travis_retry bundle
  - travis_retry ./configure --llvm-config $LLVM_CONFIG

script: rake ci

after_success:
  - if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then rake deploy; fi

branches:
  only:
    - master
    - 1.8.7
    - /^v\d+\./

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#rubinius"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9502afd22ca6c8e85fb3
    on_success: change
    on_failure: always
    on_start: always

env:
  - RVM=2.0.0 LANG="en_US.UTF-8"

os:
  - linux
  - osx

osx_image: xcode61
